const tierList = {
  Unrated: 0,
  "Bronze V": 1,
  "Bronze IV": 2,
  "Bronze III": 3,
  "Bronze II": 4,
  "Bronze I": 5,
  "Silver V": 6,
  "Silver IV": 7,
  "Silver III": 8,
  "Silver II": 9,
  "Silver I": 10,
  "Gold V": 11,
  "Gold IV": 12,
  "Gold III": 13,
  "Gold II": 14,
  "Gold I": 15,
  "Platinium V": 16,
  "Platinium IV": 17,
  "Platinium III": 18,
  "Platinium II": 19,
  "Platinium I": 20,
  "Diamond V": 21,
  "Diamond IV": 22,
  "Diamond III": 23,
  "Diamond II": 24,
  "Diamond I": 25,
  "Ruby V": 26,
  "Ruby IV": 27,
  "Ruby III": 28,
  "Ruby II": 29,
  "Ruby I": 30,
  Master: 31,
};

module.exports = {
  tierList,
};
